'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx=vm.createContext({console,window:{addEventListener(){}},LAWS:{},RN_TASK_FORMULAS:{},Map,Set});
for(const file of ['board-hardware','hardware','driver-presets','boards','designs']) vm.runInContext(fs.readFileSync('js/'+file+'.js','utf8'),ctx);
vm.runInContext('this.api={hardwareOwner,hardwarePart,hardwarePlan,hardwareSettings,fixComputers,readDesignFile,DRIVER_PRESETS};',ctx);
const A=ctx.api;
const C={boards:[{id:1,kind:'s3',name:'FC',tasks:['core','tlm']},{id:2,kind:'pizero',name:'Pi',tasks:['nav']}]};
const parts=[...Array.from({length:4},(_,i)=>({id:i+1,type:'motor',name:'M'+i,pos:[0,0,0]})),...['imu','baro','mag','fix'].map((kind,i)=>({id:i+5,type:'sensor',kind,name:kind,pos:[0,0,0]}))];
assert.equal(A.hardwareOwner(C,parts[7]).id,2);
let p=A.hardwarePlan(C,parts,C.boards[0]);assert.equal(p.errors.length,0);
C.wiring={parts:{5:{board:1,driver:'mpu',address:0x68},6:{board:1,driver:'bmp180',address:0x77},7:{board:1,driver:'hmc',address:0x1e}},boards:{1:{sda:15,scl:16,driverCode:A.DRIVER_PRESETS['10dof'].code}}};
p=A.hardwarePlan(C,parts,C.boards[0]);assert.equal(p.errors.length,0);assert.equal(p.warnings.length,0);
const settings=A.hardwareSettings(p);assert.ok(settings.indexOf('esc_hz=50')<settings.indexOf('esc_us=1000,2000'));assert.ok(settings.indexOf('esc_us=1000,2000')<settings.indexOf('esc_hz=400'));assert.ok(settings.includes('i2c=15,16'));assert.ok(settings.includes('baro=2,119'));assert.ok(settings.includes('mag=1,30'));
C.wiring.parts[1]={board:1,pin:15};assert.ok(A.hardwarePlan(C,parts,C.boards[0]).errors.some(e=>e.includes('I2C')));
C.wiring.parts[1]={board:1,pin:5};assert.ok(A.hardwarePlan(C,parts,C.boards[0]).errors.some(e=>e.includes('more than once')));
C.wiring.parts[1]={board:null};assert.ok(A.hardwarePlan(C,parts,C.boards[0]).errors.some(e=>e.includes('distributed')));
delete C.wiring.parts[1];
C.wiring.parts[7].scale='NaN,1,1';assert.ok(A.hardwarePlan(C,parts,C.boards[0]).errors.some(e=>e.includes('scale')));delete C.wiring.parts[7].scale;
C.wiring.parts[5].driver='custom';C.wiring.parts[5].address=0x77;assert.ok(A.hardwarePlan(C,parts,C.boards[0]).errors.some(e=>e.includes('same I²C address')));C.wiring.parts[5].address=0x68;
const roundtrip=JSON.parse(JSON.stringify(C));assert.equal(A.hardwarePlan(roundtrip,parts,roundtrip.boards[0]).errors.length,0);
const design=A.readDesignFile(JSON.stringify({frame:0.45,comps:parts,computers:C})).design;
assert.equal(design.computers.wiring.boards[1].driverCode,C.wiring.boards[1].driverCode);
// Deleting a board keeps other IDs stable: explicit wiring never points at a different board.
const changed=JSON.parse(JSON.stringify(C));changed.boards.push({id:3,kind:'pizero2',tasks:[]});changed.boards=changed.boards.filter(b=>b.id!==2);
const fixed=A.fixComputers(changed);assert.equal(fixed.boards[1].id,3);assert.equal(A.hardwareOwner(fixed,{id:99,type:'sensor',kind:'imu'}).id,1);
fixed.wiring.parts[99]={board:2};assert.equal(A.hardwareOwner(fixed,{id:99,type:'sensor',kind:'imu'}),null);
const next=fixed.nextBoardId;fixed.boards.push({id:next,kind:'pizero2',tasks:[]});assert.ok(next>3);assert.equal(A.hardwareOwner(A.fixComputers(fixed),{id:99,type:'sensor',kind:'imu'}),null);
const wide={...p,servoConfigs:Array.from({length:8},()=>({center:1500,scale:636.6197723675814})),sensors:{mag:{driver:'hmc',address:30,matrix:[.123456789123456,.99187657831231,0,-.99187657831231,.123456789123456,0,0,0,1]}}};assert.ok(A.hardwareSettings(wide).every(line=>Buffer.byteLength(line)<=127),'settings must fit RN_LINK_SETTING frames');
const src=fs.readFileSync('runner/fc/esp32/main/custom_sensors.h','utf8');assert.equal(src,A.DRIVER_PRESETS['10dof'].code);
console.log('Hardware wiring checks passed: bus/GPIO conflicts, profiles/addresses, disconnection, calibration, C source persistence, stable board IDs.');
vm.runInContext('this.more={hardwarePinClaims,piLatchSettings,groundHardware,groundHardwareSettings,groundHardwareErrors};',ctx);
const M=ctx.more;
C.ground={kind:'s3',name:'Command module'};
C.wiring.boards[1].batteryPin=1;C.wiring.boards[1].batteryDivider=11;C.wiring.boards[1].crsfRx=2;C.wiring.boards[1].crsfTx=21;
p=A.hardwarePlan(C,parts,C.boards[0]);assert.equal(p.errors.length,0);
assert.ok(A.hardwareSettings(p).includes('battery=1,11'));assert.ok(A.hardwareSettings(p).includes('crsf=2,21'));
C.wiring.boards[1].crsfRx=1;assert.ok(A.hardwarePlan(C,parts,C.boards[0]).errors.some(e=>e.includes('Battery ADC')&&e.includes('Receiver RX')));C.wiring.boards[1].crsfRx=2;
C.wiring.boards[1].batteryPin=17;assert.ok(A.hardwarePlan(C,parts,C.boards[0]).errors.some(e=>e.includes('ADC1')));C.wiring.boards[1].batteryPin=1;
const latch={id:20,type:'latch',name:'Hook'};C.boards[1].tasks.push('cargo');
assert.equal(A.hardwareOwner(C,latch).id,2);assert.equal(M.piLatchSettings(C,[...parts,latch],C.boards[1]),'pwm0');
C.wiring.parts[20]={board:2,driver:'gpio',pin:14};assert.ok(A.hardwarePlan(C,[...parts,latch],C.boards[1]).errors.some(e=>e.includes('serial TX')));
C.wiring.parts[20].pin=27;assert.equal(M.piLatchSettings(C,[...parts,latch],C.boards[1]),'gpio27');
C.wiring.parts[20].board=null;assert.equal(M.piLatchSettings(C,[...parts,latch],C.boards[1]),'dry');
assert.equal(M.groundHardwareErrors(C).length,0);C.ground.wiring={arm:[14]};assert.ok(M.groundHardwareSettings(C).includes('set arm=14'));
assert.equal(A.fixComputers(C).ground.wiring.arm[0],14);
C.ground.wiring.arm=[6];assert.ok(M.groundHardwareErrors(C).some(e=>e.includes('overlap')));
C.ground.wiring.arm=[14];C.ground.wiring.roll=[38];assert.ok(M.groundHardwareErrors(C).some(e=>e.includes('unavailable')));
C.wiring.parts[8]={port:'/dev/serial0'};assert.ok(A.hardwarePlan(C,parts,C.boards[1]).errors.some(e=>e.includes('already used')));
console.log('Auxiliary device checks passed: ADC/UART pin conflicts, Pi latch GPIO/PWM commands, command-module persistence, serial reservation.');
// GPIO UART can be reassigned only when the flight link moves to a different serial port.
C.wiring.boards[2]={linkPort:'/dev/ttyUSB2'};
assert.equal(A.hardwarePlan(C,parts,C.boards[1]).errors.length,0);
C.wiring.parts[20]={board:2,driver:'gpio',pin:14};
assert.ok(A.hardwarePlan(C,[...parts,latch],C.boards[1]).errors.some(e=>e.includes('UART TX')));
C.wiring.parts[8].port='/dev/ttyUSB0';
assert.equal(A.hardwarePlan(C,[...parts,latch],C.boards[1]).errors.length,0);
C.boards[1].tasks.push('tlm');C.wiring.boards[2].receiverPort='/dev/ttyUSB0';
assert.ok(A.hardwarePlan(C,parts,C.boards[1]).errors.some(e=>e.includes('already used')));
// Disconnected latches hold position instead of responding to the cargo task.
ctx.cfg={comps:[latch],computers:C};
vm.runInContext(fs.readFileSync('js/cargo.js','utf8'),ctx);
vm.runInContext('cargo.lat.set(20,{pos:1,drive:null});cargoDrive(0);this.latchDrive=cargo.lat.get(20).drive;',ctx);
assert.equal(ctx.latchDrive,0);
C.wiring.parts[20].board=null;
vm.runInContext('cargoDrive(1);this.latchDrive=cargo.lat.get(20).drive;',ctx);assert.equal(ctx.latchDrive,null);
C.wiring.parts[20].board=1;
vm.runInContext('cargoDrive(1);this.latchDrive=cargo.lat.get(20).drive;',ctx);assert.equal(ctx.latchDrive,null);
console.log('Serial reassignment and disconnected cargo latch checks passed.');
