#!/usr/bin/env node
'use strict';
const assert = require('assert'), fs = require('fs'), vm = require('vm');
const F = require('../js/flight-physics');
const close = (a,b,tol=1e-6) => assert(Math.abs(a-b) <= tol*Math.max(1,Math.abs(b)), `${a} != ${b}`);
const base = {tmax:6, prop:.035*Math.sqrt(6), fm:.6, mass:.06, tau:.03};
const mp = F.motor(base), omega = mp.Om;
const generic = F.equilibrium(mp,1,16); close(generic.T,6);
const duty = .6, x = -2 + Math.sqrt(4 + 5*duty);
close(F.equilibrium(mp,duty,16).T,6*x*x);
const cold = F.atmosphere(0), warm = F.atmosphere(35);
assert(cold.rho > warm.rho && cold.sound < warm.sound);
close(F.atmosphere(25,50662.5).rho, F.atmosphere(25).rho/2);
close(F.loadAt(mp,omega,.6125).T,3);
const fixed = {...base,motorPhysics:{kind:'brushless',kv:60/(2*Math.PI*mp.Ke),resistance:mp.R,inertia:mp.J,currentLimit:mp.iMax}};
const bigger = F.motor({...fixed,prop:base.prop*1.25}), small = F.motor(fixed);
close(bigger.Ke,small.Ke); close(bigger.R,small.R);
assert(bigger.Om < small.Om && bigger.ratedCurrent > small.ratedCurrent);
const brushed=F.motor({...fixed,motorPhysics:{...fixed.motorPhysics,kind:'brushed',brushDrop:.6}});
assert(F.equilibrium(brushed,1,16).T < F.equilibrium(small,1,16).T);
const rows=F.parsePropTable('RPM, thrust, torque\n6000, 1, .01\n12000, 4, .04');
const table=F.motor({...fixed,propPhysics:{rows,referenceDensity:1.225}});
const mid=F.loadAt(table,9000*2*Math.PI/60); close(mid.T,2.5); close(mid.Q,.025);
close(F.loadAt(table,3000*2*Math.PI/60).T,.25);
assert.throws(()=>F.propTable([[6000,1,.01],[5000,4,.04]]));
assert.throws(()=>F.parsePropTable('6000,1,-.01\n12000,4,.04'));
assert.throws(()=>F.propTable(Array.from({length:65},(_,i)=>[i+1,1,.01])));
assert.throws(()=>F.polar([[0,1,-.1],[5,2,.2]]));
const battery={capacity:1.3,cells:4}, part={type:'mass',battery:true,mass:.18};
F.batteryMass([part],battery); close(part.mass,.18);
battery.capacity=2.6; F.batteryMass([part],battery); close(part.mass,.36);
battery.cells=6; F.batteryMass([part],battery); close(part.mass,.54);
F.batteryMass([part],battery); close(part.mass,.54);
part.batteryAutoMass=false; part.mass=.2; F.batteryMass([part],battery); close(part.mass,.2);
close(F.motor({...base,tmaxC:60}).thermal.G,F.motor({...base,tmaxC:180}).thermal.G);
close(F.motor({...fixed,motorPhysics:{...fixed.motorPhysics,cooling:.4,heatCapacity:20}}).thermal.G,.4);
assert(F.compressibility(.6).thrust===1 && F.compressibility(.9).thrust<1 && F.compressibility(.9).torque>1);
const measuredFast={...table,radius:.5};const end=table.table[1][0];const loss=F.propLoss(measuredFast,end,end*.5/340,340);close(loss.thrust,1);close(loss.torque,1);
const ct=F.motor({...fixed,propPhysics:{ct:.2}}), rated=F.equilibrium(ct,1,16);close(rated.Q*rated.Omega,rated.T**1.5/(.6*Math.sqrt(2*1.225*Math.PI*base.prop**2)));
close(F.step(0,.01,16,{...mp,friction:1},.0005).Omega,0);
const ctx=vm.createContext({Math,console,FlightPhysics:F});
for(const file of ['math.js','laws.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../js',file),'utf8'),ctx);
function settle(model,dt){let o=0;for(let i=0;i<Math.round(1/dt);i++)o=F.step(o,.6,16,model,dt).Omega;return o;}
close(settle(mp,.0005),F.equilibrium(mp,.6,16).Omega,1e-5);
close(settle(table,.0005),settle(table,.00025),1e-4);
const stiff=F.motor({...fixed,motorPhysics:{kind:'brushless',kv:1000,resistance:.005,inertia:1e-8,currentLimit:500}});
close(settle(stiff,.0005),settle(stiff,.00025),1e-4);
ctx.mp=table;ctx.Omega=1000; const law=vm.runInContext('motorDynamics(Omega,.6,16,mp,.0005)',ctx), step=F.step(1000,.6,16,table,.0005);
for(const key of ['Omega','i','tau','T'])close(law[key],step[key]);
const power=F.equilibrium(mp,.6,16); close(.6*16*power.i,mp.R*power.i**2+mp.Ke*power.i*power.Omega,1e-5);
ctx.i=power.i;const soc=vm.runInContext('(() => {const s={soc:1}; batteryModel(s,i,10,{cells:4,capacity:4680,rInt:.06});return s.soc;})()',ctx);close(soc,1-power.i*10/4680);
const contact=vm.runInContext('groundContact(.001,[100,0,1])',ctx);close(contact[0],0);close(contact[2],0);
const loaded=vm.runInContext('groundContact(.01,[100,0,0])',ctx);assert(Math.abs(loaded[0])<=.6*loaded[2]+1e-9);
const wing=vm.runInContext('wingAero([-10,0,0],.1,.7,1.225,[[0,.5,.1],[10,1,.2]])',ctx);close(wing.F[2],.5*.5*1.225*100*.07);
console.log('Flight physics: motor/prop reference equations, fixed hardware, density, curves, mass, thermal independence, power balance, step convergence, friction and polar checks passed');
