#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/Users/mrtksn/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,data)=>{if(e)return res.writeHead(404).end();res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(data);});});
const near=(a,b,e=1e-6)=>assert(Math.abs(a-b)<e,`${a} != ${b}`);
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});
 const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.stack);console.error(e.stack);});await page.route(/fonts\.google|goatcounter|gc\.zgo/,r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'networkidle'});await page.waitForFunction(()=>typeof fleet!=='undefined'&&fleet.ready&&brt.ready&&objectLibrary.ready);

 const wav=Buffer.alloc(44+8820*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(44100,24);wav.writeUInt32LE(88200,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);for(let i=0;i<8820;i++)wav.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*440/44100)*12000),44+i*2);
 await page.evaluate(async()=>{
  running=false;setTerrain('open',1);
  const V=[[0,0,0],[1,0,0],[1,.1,0],[0,.1,0],[0,0,1],[1,0,1],[1,.1,1],[0,.1,1]],F=[[1,3,2],[1,4,3],[5,6,7],[5,7,8],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,4,8],[3,8,7],[4,1,5],[4,5,8]];
  const rec={id:'sound-gate-source',name:'Gate',files:[{name:'gate.obj',data:new TextEncoder().encode(V.map(v=>'v '+v.join(' ')).concat(F.map(f=>'f '+f.join(' '))).join('\n')).buffer}]};worldObjects.files.set(rec.id,rec);await worldFilePut(rec);
  const {base,size}=standModel(await parseModel(rec),'z'),o={id:'sound-gate',fileId:rec.id,name:'Gate',pos:[3,0,1],yaw:0,scale:1,units:'m',up:'z',detail:'medium',collision:'mesh',size,boxes:[]};objGroup(o);showModel(o,base);worldObjSolidify(o);worldObjects.list.push(o);worldObjectsChanged();fleetSelect(null);worldEditSet(true);worldEditSelect(o.id);worldMotionOpen(o);
 });
 await page.waitForFunction(()=>worldSounds.ready&&maps.ready);
 await page.locator('.world-sound-fields>summary').click();await page.locator('#worldSound-start>summary').click();await page.locator('#worldSound-start-source').selectOption('generated');await page.locator('#worldSound-start-preset').selectOption('beep');await page.locator('#worldSound-start-duration-n').fill('1');await page.locator('#worldSound-start-duration-n').dispatchEvent('change');
 // Real procedural graph emits nonzero PCM through the preview bus while physics is paused.
 await page.evaluate(()=>{window.soundClock=fleet.time;window.soundAnalysis=null;});await page.locator('#worldSound-start-preview').click();await page.evaluate(()=>{window.soundAnalysis=snd.ctx.createAnalyser();soundAnalysis.fftSize=1024;snd.previewMaster.connect(soundAnalysis);sndTick();});await page.waitForTimeout(120);
 let r=await page.evaluate(()=>{const d=new Float32Array(soundAnalysis.fftSize);soundAnalysis.getFloatTimeDomainData(d);return {rms:Math.sqrt(d.reduce((a,x)=>a+x*x,0)/d.length),clock:fleet.time===soundClock,paused:!running,master:snd.master.gain.value,preview:snd.previewMaster.gain.value,voice:[...worldSounds.voices].some(v=>v.preview&&v.sources.some(s=>s instanceof OscillatorNode))};});assert(r.rms>.0001&&r.clock&&r.paused&&r.master<.001&&r.preview>.1&&r.voice,JSON.stringify(r));
 await page.locator('#worldMotionTimeline').fill('0.4');await page.locator('#worldMotionTimeline').dispatchEvent('input');assert(await page.evaluate(()=>worldSounds.voices.size===0));
 await page.locator('#worldSound-start-file').setInputFiles({name:'gate.wav',mimeType:'audio/wav',buffer:wav});await page.waitForFunction(()=>!worldSounds.uploads&&worldObj('sound-gate').animation.sounds.start.source==='file');
 const fileId=await page.evaluate(()=>worldObj('sound-gate').animation.sounds.start.fileId);assert(await page.locator('#worldSound-start-source').inputValue()==='file');near(await page.evaluate(id=>worldSounds.buffers.get(id).duration,fileId),.2,1e-3);
 await page.locator('#worldSound-start-preview').click();await page.waitForFunction(()=>[...worldSounds.voices].some(v=>v.fileSource?.buffer instanceof AudioBuffer));await page.evaluate(()=>sndTick());await page.waitForTimeout(60);assert(await page.evaluate(()=>{const a=new Float32Array(soundAnalysis.fftSize);soundAnalysis.getFloatTimeDomainData(a);return a.some(v=>Math.abs(v)>.001);}), 'Uploaded clip produced no PCM');assert(await page.evaluate(()=>{const v=[...worldSounds.voices].find(v=>v.fileSource);return v&&Math.abs(v.g.gain.value-v.cue.volume*.3*worldSoundOutput(v.o).near)<.001;}), 'Uploaded clip volume decays before its end');
 // Reuse the uploaded clip for moving; shared slider controls commit volume/pitch independently.
 await page.locator('#worldSound-moving>summary').click();await page.locator('#worldSound-moving-source').selectOption('file');await page.locator('#worldSound-moving-volume').fill('0.5');await page.locator('#worldSound-moving-volume').dispatchEvent('input');await page.locator('#worldSound-moving-pitch-n').fill('1.5');await page.locator('#worldSound-moving-pitch-n').dispatchEvent('change');
 assert(await page.evaluate(id=>{const s=worldObj('sound-gate').animation.sounds;return s.moving.fileId===id&&s.moving.volume===.5&&s.moving.pitch===1.5&&s.start.pitch===1;},fileId));
 // Failed uploads are atomic; oversized data is rejected before decode.
 r=await page.evaluate(async()=>{const o=worldObj('sound-gate'),old=JSON.stringify(o.animation.sounds);await worldSoundImport(o,'start',new File(['invalid audio'],'broken.wav',{type:'audio/wav'}));const bad=worldSounds.say;await worldSoundImport(o,'start',{size:WORLD_SOUND_MAX_BYTES+1});return {same:old===JSON.stringify(o.animation.sounds),bad,large:worldSounds.say};});assert(r.same&&r.bad.includes('cannot be decoded')&&r.large.includes('16 MB'),JSON.stringify(r));
 r=await page.evaluate(async bytes=>{const o=worldObj('sound-gate'),old=JSON.stringify(o.animation.sounds),db=worldDbDo;worldDbDo=(mode,fn,store)=>store==='audio'&&mode==='readwrite'?Promise.reject(new Error('Storage full')):db(mode,fn,store);try{await worldSoundImport(o,'start',new File([Uint8Array.from(bytes)],'gate.wav',{type:'audio/wav'}));return {same:old===JSON.stringify(o.animation.sounds),say:worldSounds.say};}finally{worldDbDo=db;}},[...wav]);assert(r.same&&r.say.includes('Storage full'),JSON.stringify(r));
 await page.locator('#worldMotionDone').click();await page.evaluate(()=>{worldEditSet(false);running=false;renderRun();});
 // Count semantic edges via the real animation step, including a reverse and a persistent block.
 r=await page.evaluate(()=>{const o=worldObj('sound-gate');o.animation={...o.animation,type:'slide',offset:[0,0,1],duration:1,ease:'linear',blocked:'push'};for(const k of Object.keys(WORLD_SOUND_EVENTS))o.animation.sounds[k]={...worldSoundDefault(k),source:'generated'};window.cues=[];const event=worldSoundEvent;worldSoundEvent=(o,k,p)=>{cues.push(k);event(o,k,p);};worldMotionReset();running=true;worldMotionCommand([o.id,1]);worldMotionStep(.4);worldMotionCommand([o.id,0]);worldMotionStep(.1);worldMotionStep(.4);worldMotionStep(.1);const reverse=cues.slice();cues=[];worldMotionCommand([o.id,1]);worldMotionStep(1);worldMotionStep(.1);const opened=cues.slice();cues=[];worldMotionReset();o.animation.blocked='stop';worldMotionCommand([o.id,1]);const block=worldMotionBlocked;worldMotionBlocked=()=>true;worldMotionStep(.1);worldMotionStep(.1);worldMotionBlocked=block;o.animation.blocked='push';running=false;worldSoundReset();worldSoundEvent=event;return {reverse,opened,blocked:cues};});assert.deepStrictEqual(r.reverse,['start','stop','start','stop','closed']);assert.deepStrictEqual(r.opened,['start','stop','opened']);assert.deepStrictEqual(r.blocked,['blocked']);
 // Loop clips follow simulation speed, survive drone selection, mute on pause, then resume at motion time.
 r=await page.evaluate(async id=>{const o=worldObj('sound-gate');o.animation.sounds.moving={...worldSoundDefault('moving'),source:'file',fileId:id,name:'gate.wav',duration:.2,pitch:1.5};worldMotionReset();running=true;speed=2;worldMotionCommand([o.id,1]);worldMotionStep(.25);worldSoundTick(true);await Promise.resolve();const v=worldSounds.loops.get(o.id);const clip={loop:v?.fileSource.loop,rate:v?.fileSource.playbackRate.value,elapsed:worldSounds.states.get(o.id).elapsed};sndSelectScope();const selection=worldSounds.loops.get(o.id)===v;running=false;worldSoundTick(false);const paused=!worldSounds.voices.size;running=true;worldSoundTick(true);await Promise.resolve();const resumed=worldSounds.loops.has(o.id);setSound(false);const muted=!worldSounds.voices.size&&!worldSounds.pending.size;running=false;speed=1;return {clip,selection,paused,resumed,muted};},fileId);assert(r.clip.loop&&r.clip.rate===3&&r.clip.elapsed===.25&&r.selection&&r.paused&&r.resumed&&r.muted,JSON.stringify(r));
 // Pending decodes cannot outlive reset or pause, and do not suppress later loops.
 r=await page.evaluate(async()=>{setSound(true);const o=worldObj('sound-gate'),buffer=worldSoundBuffer;let finish;worldSoundBuffer=()=>new Promise(r=>finish=r);running=true;worldMotionReset();worldMotionCommand([o.id,1]);worldMotionStep(.1);worldSoundTick(true);running=false;worldSoundTick(false);finish(worldSounds.buffers.values().next().value);await Promise.resolve();const paused=worldSounds.pending.size===0&&worldSounds.voices.size===0;running=true;worldSoundTick(true);worldMotionReset();finish(worldSounds.buffers.values().next().value);await Promise.resolve();const reset=worldSounds.pending.size===0&&worldSounds.voices.size===0;worldSoundBuffer=buffer;running=false;return {paused,reset};});assert(r.paused&&r.reset,JSON.stringify(r));
 // All five generated presets produce native voices; loops update frequency with speed.
 r=await page.evaluate(()=>{const o=worldObj('sound-gate');running=true;const native=[];for(const preset of Object.keys(WORLD_SOUND_PRESETS)){o.animation.sounds.start={...worldSoundDefault('start'),source:'generated',preset};const v=worldSoundPlay(o,'start');native.push(v.sources.some(s=>s instanceof OscillatorNode));v.stop();}o.animation.sounds.moving={...worldSoundDefault('moving'),source:'generated'};worldMotionReset();worldMotionCommand([o.id,1]);worldMotionStep(.1);worldSoundTick(true);const v=worldSounds.loops.get(o.id),frequency=v.sources[0].frequency.value;speed=3;worldSoundTick(true);const params=v.rateParams.length;worldMotionReset();speed=1;running=false;return {native,frequency,params,reset:worldSounds.voices.size===0};});assert(r.native.every(Boolean)&&r.frequency===150&&r.params===3&&r.reset,JSON.stringify(r));
 // Two object copies own independent voices and cue definitions; removal retires only its owner.
 r=await page.evaluate(()=>{const o=worldObj('sound-gate'),copy=worldObjDuplicate(o);copy.animation.sounds.start.volume=.1;const independent=o.animation.sounds.start.volume!==.1;running=true;worldMotionReset();worldMotionCommand([o.id,1]);worldMotionCommand([copy.id,1]);worldMotionStep(.1);worldSoundTick(true);const two=worldSounds.loops.size===2;worldObjRemove(copy);const one=worldSounds.loops.size===1&&worldSounds.loops.has(o.id);worldMotionReset();running=false;return {independent,two,one};});assert(r.independent&&r.two&&r.one,JSON.stringify(r));
 // Portable files retain even disabled uploaded clips and reject bad config/missing or undecodable data.
 await page.evaluate(id=>{const o=worldObj('sound-gate');o.animation.sounds.closed={...worldSoundDefault('closed'),source:'off',fileId:id,name:'gate.wav',duration:.2};},fileId);
 const download=page.waitForEvent('download');await page.evaluate(()=>mapExport());const exported=await download,portable=JSON.parse(fs.readFileSync(await exported.path(),'utf8'));assert(Buffer.from(portable.sounds[0].data,'base64').equals(wav));assert(portable.sounds.length===1);
 assert(await page.evaluate(d=>{const m=mapDecode(d);return m.sounds[0].id!==d.sounds[0].id&&m.world.objects[0].animation.sounds.closed.fileId===m.sounds[0].id;},portable));
 for(const mutation of ['missing','badcue','badbytes'])assert(await page.evaluate(({d,mutation})=>{if(mutation==='missing')d.sounds=[];if(mutation==='badcue')d.world.objects[0].animation.sounds.start.volume=2;if(mutation==='badbytes')d.sounds[0].data='!bad';try{mapDecode(d);return false;}catch{return true;}},{d:JSON.parse(JSON.stringify(portable)),mutation}));
 r=await page.evaluate(async d=>{const before=JSON.stringify(worldObjectsSnapshot());d.sounds[0].data=btoa('not a sound');const result=await mapImport(new File([JSON.stringify(d)],'broken-map.json'));return {atomic:JSON.stringify(worldObjectsSnapshot())===before,result,say:$('#mapSay').textContent};},JSON.parse(JSON.stringify(portable)));assert(r.atomic&&!r.result&&r.say.includes('cannot be decoded'),JSON.stringify(r));
 // Saved maps own their original sound even when the active asset record/cache is gone.
 await page.evaluate(async id=>{$('#mapName').value='Sound gate';await mapSave();await worldDbDo('readwrite',s=>s.delete(id),'audio');worldSounds.files.delete(id);worldSounds.buffers.delete(id);worldSounds.assets.delete(id);await mapSelect(maps.current);},fileId);
 assert(await page.evaluate(async id=>(await worldSoundAsset(id))?.data.byteLength>44,fileId));
 await page.evaluate(()=>{fleetSave();});await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>typeof fleet!=='undefined'&&fleet.ready&&worldSounds.ready&&worldObj('sound-gate')?.base);assert(await page.evaluate(id=>worldSounds.assets.has(id)&&worldObj('sound-gate').animation.sounds.closed.fileId===id,fileId));
 // Import into a genuinely empty browser proves portable original files, without the old IndexedDB.
 const cold=await browser.newContext(),coldPage=await cold.newPage();await coldPage.route(/fonts\.google|goatcounter|gc\.zgo/,r=>r.abort());await coldPage.goto(page.url(),{waitUntil:'networkidle'});await coldPage.waitForFunction(()=>typeof fleet!=='undefined'&&fleet.ready&&maps.ready&&worldSounds.ready);r=await coldPage.evaluate(async d=>{running=false;const ok=await mapImport(new File([JSON.stringify(d)],'gate-map.json'));const o=worldObjects.list[0],id=o.animation.sounds.closed.fileId,b=await worldSoundBuffer(id),a=await worldSoundAsset(id);return {ok,duration:b.duration,bytes:mapEncode(a.data),muted:!snd.on};},portable);assert(r.ok&&r.muted&&r.bytes===portable.sounds[0].data);near(r.duration,.2,1e-3);await cold.close();
 await page.evaluate(()=>{running=false;fleetSelect(null);worldEditSet(true);worldEditSelect('sound-gate');worldMotionOpen(worldObj('sound-gate'));$('.world-sound-fields').open=true;$('#worldSound-moving').open=true;worldEditRender();});
 await page.locator('#worldSound-moving>summary').scrollIntoViewIfNeeded();if(process.env.TEST_SCREENSHOTS)await page.screenshot({path:process.env.TEST_SCREENSHOTS+'-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.locator('#worldSound-moving-preview').scrollIntoViewIfNeeded();const bounds=await page.locator('#worldPanel').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=391);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>{const cue=$('#worldSound-moving'),scroll=$('#worldSettingsBody');scroll.scrollTop+=cue.getBoundingClientRect().top-scroll.getBoundingClientRect().top;});if(process.env.TEST_SCREENSHOTS)await page.screenshot({path:process.env.TEST_SCREENSHOTS+'-phone.png'});
 // Motion preview starts/stops the loop while preserving the paused simulation clock.
 await page.locator('#tSound').click();await page.locator('#worldMotionClosed').click();const previewClock=await page.evaluate(()=>fleet.time);await page.locator('#worldMotionPlay').click();await page.waitForFunction(()=>worldSounds.loops.has('sound-gate'));assert(await page.evaluate(t=>fleet.time===t&&!running,previewClock));await page.locator('#worldMotionPlay').click();assert(await page.evaluate(()=>worldSounds.voices.size===0));
 await page.locator('#worldSound-moving-preview').click();assert(await page.evaluate(()=>worldSounds.voices.size>0));await page.locator('#worldMotionDone').click();assert(await page.evaluate(()=>worldSounds.voices.size===0&&worldSounds.pending.size===0));
 const legacy=await browser.newContext(),legacyPage=await legacy.newPage();await legacyPage.route('**/legacy-storage',r=>r.fulfill({status:200,contentType:'text/html',body:'<!doctype html><title>Legacy storage fixture</title>'}));await legacyPage.goto(new URL('/legacy-storage',page.url()).href);
 await legacyPage.evaluate(()=>new Promise((ok,no)=>{const r=indexedDB.open('liftlab-world-objects',2);r.onupgradeneeded=()=>{r.result.createObjectStore('files',{keyPath:'id'});r.result.createObjectStore('library',{keyPath:'id'});};r.onerror=()=>no(r.error);r.onsuccess=()=>{const db=r.result,t=db.transaction(['files','library'],'readwrite');t.objectStore('files').put({id:'legacy-file',name:'Retained OBJ',files:[{name:'old.obj',data:new TextEncoder().encode('v 0 0 0').buffer}]});t.objectStore('library').put({id:'legacy-file',fileId:'legacy-file',name:'Old asset',rawSize:[1,1,1],scale:1,units:'m',up:'z'});t.oncomplete=()=>{db.close();ok();};};}));
 await legacyPage.route(/fonts\.google|goatcounter|gc\.zgo/,r=>r.abort());await legacyPage.goto(page.url(),{waitUntil:'networkidle'});await legacyPage.waitForFunction(()=>typeof fleet!=='undefined'&&fleet.ready&&worldSounds.ready&&objectLibrary.ready);assert(await legacyPage.evaluate(async()=>{const db=await worldDbOpen(),rec=await worldFileGet('legacy-file');return db.version===3&&db.objectStoreNames.contains('audio')&&new TextDecoder().decode(rec.files[0].data)==='v 0 0 0'&&objectLibrary.list.some(a=>a.id==='legacy-file');}));await legacy.close();
 assert.deepStrictEqual(errors,[]);console.log('Animation sounds: native synthesis/PCM, file upload/decode, transitions, loop/rate/mute/pause/reset, deferred cancellation, independent copies, portable cold import/reload and responsive UI passed');
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
