#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/Users/mrtksn/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,data)=>{if(e)return res.writeHead(404).end();res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(data);});});
const near=(a,b,e=1e-6)=>assert(Math.abs(a-b)<e,`${a} != ${b}`);
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.stack);console.error(e.stack);});await page.route(/fonts\.google|goatcounter|gc\.zgo/,r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'networkidle'});await page.waitForFunction(()=>typeof fleet!=='undefined'&&fleet.ready&&brt.ready&&objectLibrary.ready);
 const droneDesign=await page.evaluate(()=>{running=false;setTerrain('open',1);return designSnap();});
 // Real OBJ source, persisted through the existing model loader and map packer.
 await page.evaluate(async()=>{
   const V=[[0,0,0],[1,0,0],[1,.1,0],[0,.1,0],[0,0,1],[1,0,1],[1,.1,1],[0,.1,1]],F=[[1,3,2],[1,4,3],[5,6,7],[5,7,8],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,4,8],[3,8,7],[4,1,5],[4,5,8]];
   const rec={id:'motion-gate-source',name:'Gate',files:[{name:'gate.obj',data:new TextEncoder().encode(V.map(v=>'v '+v.join(' ')).concat(F.map(f=>'f '+f.join(' '))).join('\n')).buffer}]};worldObjects.files.set(rec.id,rec);await worldFilePut(rec);
   const {base,size}=standModel(await parseModel(rec),'z'),o={id:'motion-gate',fileId:rec.id,name:'Gate',pos:[3,0,1],yaw:0,scale:1,units:'m',up:'z',detail:'medium',collision:'mesh',size,boxes:[]};objGroup(o);showModel(o,base);worldObjSolidify(o);worldObjects.list.push(o);worldObjectsChanged();fleetSelect(null);worldEditSet(true);worldEditSelect(o.id);worldEditLookAt(o);
 });
 await page.locator('#worldMotionEdit').click();await page.locator('#worldMotionPick').click();const hit=await page.evaluate(()=>{fleetScene();camera.updateMatrixWorld();const o=worldObj('motion-gate'),p=o.g.localToWorld(new THREE.Vector3(0,0,.5)).project(camera),v=vpEl.getBoundingClientRect();return {x:v.left+(p.x+1)*v.width/2,y:v.top+(1-p.y)*v.height/2};});await page.mouse.click(hit.x,hit.y);assert(await page.evaluate(()=>!worldMotionEditor.pick&&Math.abs(worldObj('motion-gate').animation.pivot[2]-.5)<.1));await page.locator('#worldMotion-pivot-2').fill('0');await page.locator('#worldMotion-pivot-2').dispatchEvent('change');await page.locator('#worldMotion-pivot-1').fill('0');await page.locator('#worldMotion-pivot-1').dispatchEvent('change');await page.locator('#worldMotion-pivot-0').fill('-.5');await page.locator('#worldMotion-pivot-0').dispatchEvent('change');await page.locator('#worldMotionTimeline').fill('1');await page.locator('#worldMotionTimeline').dispatchEvent('input');
 let r=await page.evaluate(()=>{const o=worldObj('motion-gate'),R=o.motionPose.R,center=add(o.motionPose.origin,m3v(R,[0,0,.5])),probe=add(o.motionPose.origin,m3v(R,[0,.3,.5])),d=m3v(R,[0,-1,0]);return {center,oldEmpty:!solidAt([3,0,1.5],terrainNear([3,0,1.5],.1)),ray:terrainRay(probe,d,1),draw:o.g.localToWorld(new THREE.Vector3(0,0,.5)).toArray(),solid:solidVis.position.toArray(),origin:o.motionPose.origin,triangles:o.triangles.slice(),walls:terrainWalls(probe,add(probe,scl(d,.6)),5)};});
 assert(r.oldEmpty&&r.walls===1,JSON.stringify(r));near(r.ray,.25,1e-5);r.center.forEach((v,i)=>near(v,r.draw[i]));r.solid.forEach((v,i)=>near(v,r.origin[i]));
 // Runtime keeps geometry intact, rotating both filled boxes and triangle contacts.
 r=await page.evaluate(()=>{const o=worldObj('motion-gate'),original=o.triangles.slice();o.animation.angle=45;worldMotionApply(o,1);worldObjectsChanged(false);const R=o.motionPose.R,p=add(o.motionPose.origin,m3v(R,[0,.06,.5])),c=terrainContacts(p,.02,terrainNear(p,.1))[0];o.collision='boxes';worldObjectsChanged(false);const b=terrainContacts(p,.02,terrainNear(p,.1))[0],ray=terrainRay(add(o.motionPose.origin,m3v(R,[0,.3,.5])),m3v(R,[0,-1,0]),1);const walls=terrainWalls(add(o.motionPose.origin,m3v(R,[0,.3,.5])),add(o.motionPose.origin,m3v(R,[0,-.3,.5])),5);return {walls,normal:c.n,boxNormal:b.n,ray,unchanged:JSON.stringify(original)===JSON.stringify(o.triangles)};});assert(r.unchanged&&r.walls===1,JSON.stringify(r));assert(await page.evaluate(()=>{const b={mesh:collisionMesh([0,0,0,0,1,0,0,0,1,1,0,0,1,1,0,1,0,1]),origin:[0,0,0]};return terrainSegmentHit(b,[0,.2,.2],[1,0,0],2);}), 'A surface at the ray origin hid a later mesh wall');near(r.ray,.25,1e-5);near(r.normal[0],-Math.SQRT1_2);near(r.normal[1],Math.SQRT1_2);r.normal.forEach((v,i)=>near(v,r.boxNormal[i]));
 await page.evaluate(()=>{const o=worldObj('motion-gate');o.collision='boxes';worldEditRender();});await page.locator('#worldMotion-type').selectOption('slide');await page.locator('#worldMotion-offset-2').fill('1');await page.locator('#worldMotion-offset-2').dispatchEvent('change');await page.locator('#worldMotionOpen').click();
 near(await page.evaluate(()=>surfaceBelow([3,0,10])),3);await page.evaluate(()=>{worldObj('motion-gate').collision='mesh';worldObjectsChanged(false);worldEditSolidShown(worldObj('motion-gate'));});
 if(process.env.TEST_SCREENSHOTS)await page.screenshot({path:process.env.TEST_SCREENSHOTS+'-desktop.png'});
 await page.locator('#worldMotionClosed').click();await page.locator('#worldMotionPlay').click();await page.waitForFunction(()=>worldMotionState(worldObj('motion-gate')).t>.05);await page.locator('#worldMotionPlay').click();assert(await page.evaluate(()=>!worldMotionEditor.playing));await page.locator('#worldMotionDone').click();
 assert(await page.evaluate(()=>worldMotionState(worldObj('motion-gate')).t===0&&worldMotionEditor.id===null));await page.evaluate(()=>{worldEditSet(false);running=false;renderRun();});
 assert(await page.locator('[data-world-motion="motion-gate"]').isVisible());await page.locator('[data-world-motion="motion-gate"]').click();assert(await page.evaluate(()=>worldMotionState(worldObj('motion-gate')).target===1));
 r=await page.evaluate(()=>{const o=worldObj('motion-gate');o.animation.ease='linear';o.animation.duration=1;o.animation.blocked='push';worldMotionStep(.25);const p=add(o.motionPose.origin,[0,.06,.5]),c=terrainContacts(p,.02,terrainNear(p,.1))[0];return {t:worldMotionState(o).t,velocity:c.velocity,top:surfaceBelow([3,0,10])};});near(r.t,.25);near(r.velocity[2],1);near(r.top,2.25);assert(await page.evaluate(()=>withDrone(fleet.drones[0],()=>designSnap()))===droneDesign,'World animation changed drone design');
 // Loop uses simulation time once per fleet tick, independent of craft count.
 r=await page.evaluate(()=>{const o=worldObj('motion-gate');o.animation.mode='loop';o.animation.waitClosed=.1;o.animation.waitOpen=.1;worldMotionReset();for(let i=0;i<300;i++)worldMotionStep(.01);return {t:worldMotionState(o).t,target:worldMotionState(o).target};});assert(r.t>=0&&r.t<=1);
 r=await page.evaluate(()=>{const o=worldObj('motion-gate');o.animation.mode='button';worldMotionReset();worldMotionCommand([o.id,1]);fleetStep(20);const t=worldMotionState(o).t;fleetCreate('quadx');worldMotionReset();worldMotionCommand([o.id,1]);fleetStep(20);return {one:t,two:worldMotionState(o).t};});near(r.one,r.two);
 // The zone waits for the final drone to leave, with close delay and boundary hysteresis.
 r=await page.evaluate(()=>{const o=worldObj('motion-gate');o.animation.mode='proximity';o.animation.radius=1;o.animation.delay=.5;worldMotionReset();fleet.drones.forEach(d=>d.state.S.p=[20,20,2]);fleet.drones[0].state.S.p=[3,0,1];worldMotionStep(.1);const entered=worldMotionState(o).target;fleet.drones[1].state.S.p=[3,0,1];fleet.drones[0].state.S.p=[20,20,2];worldMotionStep(.6);const occupied=worldMotionState(o).target;fleet.drones[1].state.S.p=[20,20,2];worldMotionStep(.2);const delayed=worldMotionState(o).target;worldMotionStep(.3);return {entered,occupied,delayed,left:worldMotionState(o).target};});assert.deepStrictEqual(r,{entered:1,occupied:1,delayed:1,left:0});
 // Predicted obstruction uses actual drone contact points; stop and reverse do not drive into it.
 r=await page.evaluate(()=>{const o=worldObj('motion-gate');o.pos=[0,-.6,.1];o.animation={...worldMotionValidate(WORLD_MOTION_DEFAULT),type:'slide',offset:[0,1,0],duration:1,ease:'linear',blocked:'stop'};for(const d of fleet.drones)withDrone(d,()=>{resetSim();S.p=[0,0,.6];});worldMotionReset();worldMotionCommand([o.id,1]);worldMotionStep(.7);const stop={t:worldMotionState(o).t,blocked:worldMotionState(o).blocked};o.animation.blocked='reverse';worldMotionCommand([o.id,1]);worldMotionStep(.7);const reverse=worldMotionState(o).target;o.animation.blocked='push';worldMotionCommand([o.id,1]);worldMotionStep(.7);return {stop,reverse,push:worldMotionState(o).t,points:worldMotionObstacles().length};});assert(r.stop.blocked&&r.stop.t===0&&r.reverse===0&&r.push>.6&&r.points>0,JSON.stringify(r));
 // Proximity reversal must retreat rather than immediately retrying the occupied trigger.
 r=await page.evaluate(()=>{const o=worldObj('motion-gate');o.animation.mode='proximity';o.animation.zone=[0,.6,.5];o.animation.radius=2;o.animation.blocked='reverse';worldMotionReset();worldMotionStep(.7);const reversed=worldMotionState(o).target;worldMotionStep(.1);worldMotionStep(.1);const held=worldMotionState(o).target;o.animation.mode='button';o.animation.zone=[0,0,0];return {reversed,held};});assert(r.reversed===0&&r.held===0,JSON.stringify(r));
 // Scenery and ground also block prescribed motion.
 r=await page.evaluate(()=>{const o=worldObj('motion-gate');o.pos=[3,0,1];o.animation.blocked='stop';worldMotionReset();terrain.city=[{lo:[2.8,.25,1],hi:[3.2,.35,2],what:'Fixed wall'}];terrainCompose();worldMotionCommand([o.id,1]);worldMotionStep(.7);const wall=worldMotionState(o).blocked;o.pos=[3,0,0];o.animation.offset=[0,0,-1];terrain.city=[];worldMotionReset();worldMotionCommand([o.id,1]);worldMotionStep(.1);const ground=worldMotionState(o).blocked;o.animation.offset=[0,1,0];return {wall,ground};});assert(r.wall&&r.ground,JSON.stringify(r));
 // Real contact response: a moving gate imparts velocity without nonfinite states.
 r=await page.evaluate(()=>{const o=worldObj('motion-gate');o.pos=[0,-.6,.1];o.animation.mode='button';o.animation.blocked='push';fleetResetAll();fleet.drones.forEach((d,i)=>withDrone(d,()=>{S.p=i?[20,20,.6]:[0,0,.6];setpoint.z=.6;}));worldMotionCommand([o.id,1]);let max=0,finite=true;for(let i=0;i<.7/PDT;i++){fleet.drones[0].state.S.p[2]=.6;fleet.drones[0].state.S.v[2]=0;fleetStep(1);max=Math.max(max,fleet.drones[0].state.S.v[1]);finite&&=fleet.drones.every(d=>[...d.state.S.p,...d.state.S.v,...d.state.S.q].every(Number.isFinite));}return {finite,max};});assert(r.finite&&r.max>.02,JSON.stringify(r));
 // Moving solids wake nearby sleeping cargo and leave distant sleeping bodies alone.
 r=await page.evaluate(()=>withDrone(fleet.drones[0],()=>{const o=worldObj('motion-gate');o.pos=[3,0,1];worldMotionReset();const c=mkMass('Resting parcel',0,0,0,{mass:.1,size:[.1,.1,.1]}),L=looseBody('Resting parcel',[c]),far=looseBody('Distant parcel',[c]);L.p=[3,.2,1.5];far.p=[20,20,1.5];for(const b of [L,far]){b.asleep=true;b.motionVer=terrain.motionVer||0;}worldMotionCommand([o.id,1]);worldMotionStep(.15);looseStep(L,PDT);looseStep(far,PDT);return {near:!L.asleep,far:far.asleep,finite:[...L.p,...L.v,...L.q].every(Number.isFinite)};}));assert(r.near&&r.far&&r.finite,JSON.stringify(r));
 // Button actions record/replay, while runtime collider movement never invalidates a recording.
 r=await page.evaluate(()=>{const o=worldObj('motion-gate');o.pos=[3,0,1];worldMotionReset();recordStart();running=false;userAction('worldMotion',[o.id,1]);worldMotionStep(.1);const active=rec.on,event=rec.take.ev.find(e=>e[2]==='worldMotion');recordStop();worldMotionReset();replayApply(event);return {active,kind:event[2],target:worldMotionState(o).target};});assert(r.active&&r.kind==='worldMotion'&&r.target===1,JSON.stringify(r));
 // Duplication, map serialization/validation and reload preserve independent definitions, never preview poses.
 r=await page.evaluate(()=>{const o=worldObj('motion-gate'),c=worldObjDuplicate(o);c.animation.offset[0]=8;const independent=o.animation.offset[0]===0;worldObjRemove(c);const snap=worldObjectsSnapshot()[0];return {independent,snap,rest:o.pos};});assert(r.independent&&r.snap.animation.type==='slide');assert.deepStrictEqual(r.snap.pos,r.rest);
 const portable=await page.evaluate(async()=>{const m=await mapCollect('Animated gate');return {format:MAP_FORMAT,version:1,...m,files:m.files.map(f=>({...f,files:f.files.map(p=>({name:p.name,data:mapEncode(p.data)}))}))};});assert(await page.evaluate(d=>mapDecode(d).world.objects[0].animation.offset[1]===1,portable));assert(await page.evaluate(d=>{d.world.objects[0].animation.duration=NaN;try{mapDecode(d);return false;}catch{return true;}},JSON.parse(JSON.stringify(portable))));
 await page.evaluate(()=>{running=false;fleetSave();});await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>typeof fleet!=='undefined'&&fleet.ready&&worldObj('motion-gate')?.base);assert(await page.evaluate(()=>worldObj('motion-gate').animation.type==='slide'&&worldMotionState(worldObj('motion-gate')).t===0));
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{running=false;fleetSelect(null);worldEditSet(true);worldEditSelect('motion-gate');worldMotionOpen(worldObj('motion-gate'));worldMotionFit(worldObj('motion-gate'));});
 assert(await page.locator('#worldMotionTimeline').count()===1);const bounds=await page.locator('#worldPanel').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=391);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>{fleetScene();camera.updateMatrixWorld();});const visible=await page.evaluate(()=>{const o=worldObj('motion-gate'),p=o.g.localToWorld(new THREE.Vector3(0,0,.5)).project(camera),view=vpEl.getBoundingClientRect(),panel=$('#worldPanel').getBoundingClientRect(),y=view.top+(1-p.y)*view.height/2;return {y,top:view.top,bottom:panel.top};});assert(visible.y>visible.top&&visible.y<visible.bottom,JSON.stringify(visible));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));if(process.env.TEST_SCREENSHOTS)await page.screenshot({path:process.env.TEST_SCREENSHOTS+'-phone.png'});
 await page.locator('#worldMotionRemove').click();assert(await page.evaluate(()=>!worldObj('motion-gate').animation&&!worldMotionEditor.id&&!worldMotionGuide));assert.deepStrictEqual(errors,[]);console.log('World animation: editor, transformed solids/rays, runtime surface velocity, activation, obstruction, physics, replay, maps/reload and phone passed');
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
