// Generates rn_ops.h from js/rn-ops.js, so the C runner and the compiler always agree on the instruction set.
// node runner/gen_ops.js > runner/rn_ops.h
const { RN_OPS, RN_MAGIC, RN_VERSION, RN_VKIND, RN_VIEWS } = require('../js/rn-ops.js');
const out = [];
out.push('/* Generated by gen_ops.js from js/rn-ops.js. Do not edit. */', '#ifndef RN_OPS_H', '#define RN_OPS_H', '');
out.push(`#define RN_MAGIC 0x${RN_MAGIC.toString(16)}u`, `#define RN_VERSION ${RN_VERSION}`, `#define RN_NOPS ${RN_OPS.length}`, '');
out.push('enum rn_op {');
RN_OPS.forEach(([n], i) => out.push(`  RN_${n} = ${i},`));
out.push('};', '');
out.push('static const char *const rn_op_name[RN_NOPS] = {' + RN_OPS.map(o => `"${o[0]}"`).join(', ') + '};');
out.push('/* operand kinds: d scalar written, a scalar read, t jump target, i immediate, r register written, R register read, o read or -1, g register read or -1 */');
out.push('static const char *const rn_op_spec[RN_NOPS] = {' + RN_OPS.map(o => `"${o[1]}"`).join(', ') + '};', '');
out.push('/* blocks: operand, write?, kind (n: fixed size x, $: size in operand x, L: list 1 + cap(op y) * stride(op x), R: ring 2 + …, N: 1 + op x) */');
out.push('typedef struct { signed char op, operand, write, kind; signed char x, y; } rn_blk;');
const blks = [];
RN_OPS.forEach(([n, s, b], op) => (b || []).forEach(([oi, rw, sz]) => {
  let kind, x = 0, y = 0;
  if (typeof sz === 'number') { kind = 'n'; x = sz; }
  else if (sz[0] === '$') { kind = '$'; x = +sz.slice(1); }
  else if (sz[0] === 'N') { kind = 'N'; x = +sz.slice(1); }
  else { kind = sz[0]; [x, y] = sz.slice(1).split(',').map(Number); }
  blks.push(`  {${op}, ${oi}, ${rw === 'w' ? 1 : 0}, '${kind}', ${x}, ${y}}`);
}));
out.push('/* fused list steps: kinds, and each view\'s operands (register, offset, stride, written?) */');
for (const [k, v] of Object.entries(RN_VKIND)) out.push(`#define RN_V_${k.toUpperCase()} ${v}`);
out.push('typedef struct { signed char op, reg, off, stride, write; } rn_view;');
const views = []; for (const [n, vs] of Object.entries(RN_VIEWS)) for (const [r, o, st, w] of vs) views.push(`  {RN_${n}, ${r}, ${o}, ${st}, ${w}}`);
out.push(`#define RN_NVIEW ${views.length}`, 'static const rn_view rn_op_view[RN_NVIEW] = {', views.join(',\n'), '};', '');
out.push(`#define RN_NBLK ${blks.length}`, 'static const rn_blk rn_op_blk[RN_NBLK] = {', blks.join(',\n'), '};', '', '#endif');
console.log(out.join('\n'));
