/* Generated by gen_ops.js from js/rn-ops.js. Do not edit. */
#ifndef RN_OPS_H
#define RN_OPS_H

#define RN_MAGIC 0x52464244u
#define RN_VERSION 2
#define RN_NOPS 74

enum rn_op {
  RN_NOP = 0,
  RN_MOV = 1,
  RN_ADD = 2,
  RN_SUB = 3,
  RN_MUL = 4,
  RN_DIV = 5,
  RN_MOD = 6,
  RN_POW = 7,
  RN_MIN = 8,
  RN_MAX = 9,
  RN_ATAN2 = 10,
  RN_LT = 11,
  RN_LE = 12,
  RN_EQ = 13,
  RN_NE = 14,
  RN_NEG = 15,
  RN_ABS = 16,
  RN_SQRT = 17,
  RN_SIN = 18,
  RN_COS = 19,
  RN_TAN = 20,
  RN_ASIN = 21,
  RN_ACOS = 22,
  RN_ATAN = 23,
  RN_EXP = 24,
  RN_LOG = 25,
  RN_FLOOR = 26,
  RN_CEIL = 27,
  RN_ROUND = 28,
  RN_SIGN = 29,
  RN_NOT = 30,
  RN_TRUTH = 31,
  RN_SEL = 32,
  RN_CLAMP = 33,
  RN_FMA = 34,
  RN_JMP = 35,
  RN_JZ = 36,
  RN_JNZ = 37,
  RN_TRAP = 38,
  RN_CPY = 39,
  RN_FILL = 40,
  RN_LLEN = 41,
  RN_LFILL = 42,
  RN_CPYL = 43,
  RN_PUSH = 44,
  RN_RPUSH = 45,
  RN_RSHIFT = 46,
  RN_RCLR = 47,
  RN_IDX = 48,
  RN_IDXI = 49,
  RN_RIDX = 50,
  RN_LDI = 51,
  RN_STI = 52,
  RN_CPI = 53,
  RN_CPO = 54,
  RN_AR = 55,
  RN_M3V = 56,
  RN_M3M = 57,
  RN_M3T = 58,
  RN_CRS = 59,
  RN_QMUL = 60,
  RN_QMAT = 61,
  RN_QNORM = 62,
  RN_M2Q = 63,
  RN_UNIT3 = 64,
  RN_NRM3 = 65,
  RN_DOT3 = 66,
  RN_ADD3 = 67,
  RN_SUB3 = 68,
  RN_SCL3 = 69,
  RN_BLS = 70,
  RN_VV = 71,
  RN_VS = 72,
  RN_VDOT = 73,
};

static const char *const rn_op_name[RN_NOPS] = {"NOP", "MOV", "ADD", "SUB", "MUL", "DIV", "MOD", "POW", "MIN", "MAX", "ATAN2", "LT", "LE", "EQ", "NE", "NEG", "ABS", "SQRT", "SIN", "COS", "TAN", "ASIN", "ACOS", "ATAN", "EXP", "LOG", "FLOOR", "CEIL", "ROUND", "SIGN", "NOT", "TRUTH", "SEL", "CLAMP", "FMA", "JMP", "JZ", "JNZ", "TRAP", "CPY", "FILL", "LLEN", "LFILL", "CPYL", "PUSH", "RPUSH", "RSHIFT", "RCLR", "IDX", "IDXI", "RIDX", "LDI", "STI", "CPI", "CPO", "AR", "M3V", "M3M", "M3T", "CRS", "QMUL", "QMAT", "QNORM", "M2Q", "UNIT3", "NRM3", "DOT3", "ADD3", "SUB3", "SCL3", "BLS", "VV", "VS", "VDOT"};
/* operand kinds: d scalar written, a scalar read, t jump target, i immediate, r register written, R register read, o read or -1, g register read or -1 */
static const char *const rn_op_spec[RN_NOPS] = {"", "da", "daa", "daa", "daa", "daa", "daa", "daa", "daa", "daa", "daa", "daa", "daa", "daa", "daa", "da", "da", "da", "da", "da", "da", "da", "da", "da", "da", "da", "da", "da", "da", "da", "da", "da", "daaa", "daaa", "daaa", "t", "at", "at", "i", "iii", "iai", "iaii", "iaii", "iiii", "iiii", "iiii", "iii", "iii", "riaii", "rRiaai", "riaii", "dRi", "Ria", "iRii", "Riii", "ri", "iii", "iii", "ii", "iii", "iii", "ii", "ii", "ii", "ii", "di", "dii", "iii", "iii", "iia", "iiiiiiooaii", "igiigiigiiai", "igiigiiaai", "dgiigiiai"};

/* blocks: operand, write?, kind (n: fixed size x, $: size in operand x, L: list 1 + cap(op y) * stride(op x), R: ring 2 + …, N: 1 + op x) */
typedef struct { signed char op, operand, write, kind; signed char x, y; } rn_blk;
/* fused list steps: kinds, and each view's operands (register, offset, stride, written?) */
#define RN_V_ADD 0
#define RN_V_SUB 1
#define RN_V_MUL 2
#define RN_V_DIV 3
#define RN_V_RSUB 4
#define RN_V_RDIV 5
typedef struct { signed char op, reg, off, stride, write; } rn_view;
#define RN_NVIEW 7
static const rn_view rn_op_view[RN_NVIEW] = {
  {RN_VV, 1, 2, 3, 1},
  {RN_VV, 4, 5, 6, 0},
  {RN_VV, 7, 8, 9, 0},
  {RN_VS, 1, 2, 3, 1},
  {RN_VS, 4, 5, 6, 0},
  {RN_VDOT, 1, 2, 3, 0},
  {RN_VDOT, 4, 5, 6, 0}
};

#define RN_NBLK 57
static const rn_blk rn_op_blk[RN_NBLK] = {
  {39, 0, 1, '$', 2, 0},
  {39, 1, 0, '$', 2, 0},
  {40, 0, 1, '$', 2, 0},
  {41, 0, 1, 'L', 3, 2},
  {42, 0, 1, 'L', 2, 3},
  {43, 0, 1, 'L', 2, 3},
  {43, 1, 0, 'L', 2, 3},
  {44, 0, 1, 'L', 2, 3},
  {44, 1, 0, '$', 2, 0},
  {45, 0, 1, 'R', 2, 3},
  {45, 1, 0, '$', 2, 0},
  {46, 0, 1, 'R', 1, 2},
  {47, 0, 1, 'R', 1, 2},
  {50, 1, 0, 'R', 3, 4},
  {53, 0, 1, '$', 3, 0},
  {54, 2, 0, '$', 3, 0},
  {56, 0, 1, 'n', 3, 0},
  {56, 1, 0, 'n', 9, 0},
  {56, 2, 0, 'n', 3, 0},
  {57, 0, 1, 'n', 9, 0},
  {57, 1, 0, 'n', 9, 0},
  {57, 2, 0, 'n', 9, 0},
  {58, 0, 1, 'n', 9, 0},
  {58, 1, 0, 'n', 9, 0},
  {59, 0, 1, 'n', 3, 0},
  {59, 1, 0, 'n', 3, 0},
  {59, 2, 0, 'n', 3, 0},
  {60, 0, 1, 'n', 4, 0},
  {60, 1, 0, 'n', 4, 0},
  {60, 2, 0, 'n', 4, 0},
  {61, 0, 1, 'n', 9, 0},
  {61, 1, 0, 'n', 4, 0},
  {62, 0, 1, 'n', 4, 0},
  {62, 1, 0, 'n', 4, 0},
  {63, 0, 1, 'n', 4, 0},
  {63, 1, 0, 'n', 9, 0},
  {64, 0, 1, 'n', 3, 0},
  {64, 1, 0, 'n', 3, 0},
  {65, 1, 0, 'n', 3, 0},
  {66, 1, 0, 'n', 3, 0},
  {66, 2, 0, 'n', 3, 0},
  {67, 0, 1, 'n', 3, 0},
  {67, 1, 0, 'n', 3, 0},
  {67, 2, 0, 'n', 3, 0},
  {68, 0, 1, 'n', 3, 0},
  {68, 1, 0, 'n', 3, 0},
  {68, 2, 0, 'n', 3, 0},
  {69, 0, 1, 'n', 3, 0},
  {69, 1, 0, 'n', 3, 0},
  {70, 0, 1, 'N', 10, 0},
  {70, 1, 0, 'L', 9, 10},
  {70, 2, 0, 'N', 10, 0},
  {70, 3, 0, 'N', 10, 0},
  {70, 4, 0, '$', 9, 0},
  {70, 5, 0, '$', 9, 0},
  {70, 6, 0, 'N', 10, 0},
  {70, 7, 0, 'N', 10, 0}
};

#endif
